development:
  adapter: postgresql
  database: etsydemo_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: etsydemo_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: etsydemo_production
  pool: 5
  timeout: 5000
  